config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'foods#index'
  resources :public_recipes, only: [:index]
  resources :general_shoppings, only: [:index]
  resources :foods, only: [:index, :new, :create, :show, :destroy]
  resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    member do
      patch :public_toggle
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    user ||= User.new
    can :read, :all
    return unless user.present?

    can :manage, Recipe, user_id: user.id # if the user is logged in can manage it's own posts
    can :manage, Food, user_id: user.id # logged in users can also create comments
    can :manage, RecipeFood, user_id: user.id # logged in users can also create comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'food_id', dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'recipe_id', dependent: :destroy
  has_many :foods, through: :recipe_foods

  def total_price
    recipe_foods.sum { |food| food.quantity * food.food.price }
  end

  validates :name, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :description, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, class_name: 'Food', foreign_key: 'user_id', dependent: :destroy
  has_many :recipes, class_name: 'Recipe', foreign_key: 'user_id', dependent: :destroy
  has_many :recipe_foods, through: :recipes
  validates :name, presence: true, allow_blank: false, length: { maximum: 250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show destroy]

  # GET /foods or /foods.json
  def index
    @foods = current_user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.build(food_params)

    if @food.save
      flash[:notice] = 'Food was successfully created.'
      redirect_to foods_url(@food)
    else
      flash[:alert] = 'Food was not created.'
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy
    flash[:notice] = 'Food was successfully destroyed.'
    redirect_to foods_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/general_shoppings_controller.rb
class GeneralShoppingsController < ApplicationController
  def index
    @recipe_food = current_user.recipe_foods.group(:food_id).sum(:quantity)
    @foods = current_user.foods
    @shopping = []
    @foods.each do |food|
      @shopping << food if !@recipe_food.key?(food.id) && !@shopping.include?(food)
    end
    @total_price = @shopping.sum(&:price)
    @total_item = @shopping.count
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @user = current_user
    @public_recipes = Recipe.includes(:user)
      .where(public: true)
      .order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_foods, only: %i[edit destroy update]
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_id: @recipe.id)
  end

  def create
    @recipe = Recipe.find(params[:recipe_food][:recipe_id])
    @recipe_food = @recipe.recipe_foods.build(recipe_food_params)
    if @recipe_food.save
      flash[:notice] = 'Food created successfully.'
      redirect_to recipe_url(user_id: current_user.id, id: @recipe.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @recipe_food.update(recipe_food_params)
      flash[:success] = 'Recipe Food updated successfully.'
    else
      flash[:alert] = 'Recipe Food not updated.'
    end
    redirect_to recipe_path(@recipe_food.recipe.id)
  end

  def destroy
    @recipe_food.destroy
    flash[:success] = 'Recipe Food deleted successfully.'
    recipes_url
  end

  private

  def set_recipe_foods
    @recipe_food = RecipeFood.includes(:recipe).find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show destroy public_toggle]

  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe_food = @recipe.recipe_foods.includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      flash[:notice] = 'Recipe was successfully created.'
      redirect_to recipes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe.destroy

    flash[:notice] = 'Recipe was successfully deleted.'
    redirect_to recipes_url
  end

  def public_toggle
    @recipe.public = !@recipe.public
    return unless @recipe.save

    redirect_to recipe_path(@recipe), notice: "The recipe is now #{@recipe.public ? 'public' : 'private'}"
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shoppings_helper.rb
module GeneralShoppingsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<tr  id="<%= dom_id food %>">
	<th scope="row"><%= food.id %></th>
	<td><%= food.name%></td>
	<td><%= food.measurement_unit %></td>
	<td><%= food.price %>$</td>
    <td><%= food.quantity %></td>
	<td><%= link_to "View",  food_path(food.id), class: "btn btn-outline-info  fw-semibold fs-5 px-3" %></td> 
	<%if can? :destroy, food %>
	<td><%= link_to "Delete",  food_path(food.id),  data: { "turbo-method": :delete, confirm: "Are you sure ?" }, class: "btn btn-outline-danger  fw-semibold fs-5 px-3" %></td>
	<% end %>
</tr>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit "Create food" ,  class: 'btn btn-info mt-2' %>
  </div>
<% end %>

app/views/foods/index.html.erb
<div class="container mt-5 ">
<div class="d-flex justify-content-between align-items-center pt-5">
<h1>Foods</h1>
<%= link_to "Add New food", new_food_path, class: "btn btn-primary px-2" %>
</div>
<table class=" table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Food</th>
      <th scope="col">Measurement Unit</th>
      <th scope="col">Uint Price</th>
      <th scope="col">Quantity</th>
      <th scope="col" colspan="3" >Action</th>
    </tr>
  </thead>
  <tbody id="foods">
  <% @foods.each do |food| %>
    <%= render food %>
  <% end %>
 </tbody>
</table>
</div>

app/views/foods/new.html.erb
<div class="container d-flex flex-column  justify-content-center align-items-center pt-5">

<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>
</div>

app/views/foods/show.html.erb
<div class="container d-flex flex-column  justify-content-center align-items-center pt-5">
<div class="card" style="width: 15rem;">
  <div class="card-header">
    <%= @food.name%>
  </div>
<ul class="list-group gap-3 list-group-horizontal">
  <li class="list-group-item">Measuremant Unit</li>
  <li class="list-group-item"><%= @food.measurement_unit %></li>
</ul>
<ul class="list-group gap-5 list-group-horizontal">
  <li class="list-group-item">Food Price</li>
  <li class="list-group-item"><%= @food.price %>$</li>
</ul>
<ul class="list-group gap-5 list-group-horizontal">
  <li class="list-group-item">Food Quantity </li>
  <li class="list-group-item"><%= @food.quantity %></li>
</ul>
</div>
<div>
  <%= link_to "Back to foods", foods_path %>
</div>
</div>

app/views/general_shoppings/index.html.erb
<div class="container d-flex flex-column  justify-content-center align-items-center pt-5">

<h1 class="text-center w-100">Shopping List</h1>
 <div class="d-flex justify-content-between align-items-center  w-100">
    <h2>Amount of food items to buy: <%= @total_item %></h2>
    <h2>Total value of food needed: $<%= @total_price %></h2>
</div>
<table class=" table mt-5">
  <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Uint Price</th>
    </tr>
  </thead>
  <tbody id="foods">
  <% @shopping.each do |food| %>
    <tr>
        <td><%= food.name%></td>
        <td><%= food.quantity %> <%= food.measurement_unit %></td>
        <td><%= food.price %>$</td>
    </tr>
  <% end %>
 </tbody>
</table>

</div>

app/views/public_recipes/index.html.erb
<div class="container d-flex flex-column  justify-content-center align-items-start pt-5">
<h1 class="recipe-head">Public Recipes</h1>
<section class="public-recipe-container">
<% if @public_recipes.empty? %>
    <p>No public recipes in the collection</p>
<% end %>
<% @public_recipes.each do |recipe| %>
<div id="<%= dom_id recipe %>">
<div class="card mb-3 mt-3 ms-5" style="width: 640px; margin-left: 100px;">
  <div class="row g-0">
    <div class="col-md-4 p-3 d-flex flex-column justify-content-between">
     <h2 class="card-title ps-2">By: <%= recipe.user.name %></h2>
    <div class='p-3'>
    <%= link_to "View",  recipe_path(recipe.id), class: "btn btn-outline-info  fw-semibold fs-5 px-3" %> 
    </div>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h3 class="card-title"><%= recipe.name  %></h3>
        <p class="card-text">Total food items: <%= recipe.recipe_foods.count %></p>
        <p class="card-text">Total price: $<%= recipe.total_price %></p>
      </div>
    </div>
  </div>
</div>
</div>
<% end %>
</section>
</div>

app/views/recipe_foods/edit.html.erb
<div class="container d-flex flex-column  justify-content-center align-items-start pt-5 size">
<h2 class="heading">You can edit your ingraedint here</h2>
<%= form_with model: @recipe_food, url: recipe_food_path, method: :patch, data: { turbo: false }, local: true, class:"input-form size" do |form| %>
  <% if @recipe_food.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:
      </h2>
      <ul>
        <% @recipe_food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="form-div">
  <div class="mb-3 col-sm-5">
    <%= form.label :food, class:"form-label" %><br>
    <%= form.select :food_id, options_for_select(current_user.foods.collect {|food| [food.name, food.id]}, @recipe_food.food_id), { include_blank: true }, class:"form-control" %>
  </div>
  <div class="mb-3 col-sm-5">
    <%= form.label :quantity, class:"form-label" %>
    <%= form.number_field :quantity, required: true, placeholder: '1',  min: 1, class:"form-control" %>
  </div>
  <div class="mb-3 col-sm-2">
    <%= form.submit 'Update', class:"btn btn-primary form-control" %>
  </div>
  <div>
  <%= link_to "Back to #{@recipe_food.recipe.name}", recipe_path(@recipe_food.recipe.id), class: "btn btn-primary mt-5" %>
</div>
</div>
<% end %>
</div>

app/views/recipe_foods/new.html.erb
<div class="container d-flex flex-column  justify-content-center align-items-start pt-5 size">

<h1>You can Add ingredients here</h1>
<%= form_with model: @recipe_food, url: recipe_foods_path, method: :post, class:"input-form size", data: { turbo: false }  do |f|%>
    <div class="form-div" >
    <%= f.hidden_field :recipe_id, value: @recipe.id %>


    <div class="mb-3 col-sm-8">
    <%= f.label :food, class:"form-label" %><br>
    <%= f.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: true} , class:"form-select w-100" %><br>

    </div>

    <div class="mb-3 col-sm-8">
    <%= f.label :quantity, class:"form-label" %><br>
    <%= f.number_field :quantity ,  class:"form-control" , required: true, placeholder: '1',  min: 1%><br>
    </div>

    <div class="mb-3 col-sm-2  text-center d-flex justify-content-start ">
    <%= f.submit "Submit", class:"btn btn-primary form-control" %>
    </div>
    <div>
    <%= link_to "Back to #{@recipe_food.recipe.name}", recipe_path(@recipe_food.recipe.id), class: "btn btn-primary mt-5" %>
    </div>
    </div>

<%end%>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.number_field  :preparation_time %>
  </div>
  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.number_field :cooking_time %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <div class="form-check">
    <%= form.check_box :public, class: "form-check-input" %>
    <%= form.label :public, class: "form-check-label" ,style: "display: block" %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
<div class="card mb-3 mt-3 ms-5" style="width: 940px; margin-left: 100px;">
  <div class="row g-0">
    <div class="col-md-4 p-3 d-flex flex-column justify-content-between">
     <h3 class="card-title ps-2"><%= recipe.name  %></h3>
    <div class='p-3'>
    <%= link_to "View",  recipe_path(recipe.id), class: "btn btn-outline-info  fw-semibold fs-5 px-3" %>
    <%if can? :destroy, recipe %> 
    <%= link_to "Delete",  recipe_path(recipe.id),  data: { "turbo-method": :delete, confirm: "Are you sure ?" }, class: "btn btn-outline-danger  fw-semibold fs-5 px-3" %>
    <% end %>
    </div>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= recipe.name  %></h5>
        <p class="card-text"><%= recipe.description  %></p>
      </div>
    </div>
  </div>
</div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<div class="container mt-5 ">
<div class="d-flex justify-content-between align-items-center pt-5">
<h1>Recipes</h1>
<%= link_to "New recipe", new_recipe_path, class: "btn btn-primary px-2" %>
</div>


<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</div>
</div>

app/views/recipes/new.html.erb
<div class="container d-flex flex-column  justify-content-center align-items-center pt-5">

<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>
</div>

app/views/recipes/show.html.erb
<div class="container d-flex flex-column  justify-content-center align-items-start pt-5">
  <h1 class="text-center"><%= @recipe.name %></h1>
  <div class="d-flex justify-content-between align-items-center  size">
    <p>Preparation time: <%= @recipe.preparation_time %>
      <%=  @recipe.preparation_time <= 1 ? 'hour' : 'hours' %>
    </p>
     <div class="d-flex align-items-center">
        <span class="me-1">
          <strong> <%= @recipe.public ? 'Public' : 'Private'  %></strong>
        </span>
      <%= button_to 'Click to Toggle', public_toggle_recipe_path(@recipe), method: :patch, class: "ms-3 btn btn-primary"%>
      </div>
    </div>
    <p>Cooking time: <%= @recipe.cooking_time %>
    <%= @recipe.preparation_time <= 1 ? 'hour' : 'hours' %>
    </p>
<div class="d-flex justify-content-between align-items-center  size">
  <%= link_to "Generate Shopping List", general_shoppings_path ,class: "btn btn-primary" %>
   <% if can? :create, @recipe%>
  <%= link_to "Add Ingredient", new_recipe_food_path(recipe_id:@recipe.id), class: "btn btn-primary" %>
  <% end%>
</div>

<div class="container mt-5 ">
<table class=" table">
  <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Uint Price</th>
      <th scope="col">Measurement Unit</th>
      <th scope="col" colspan="3" >Action</th>
    </tr>
  </thead>
  <tbody id="foods">
  <% @recipe_food.each do |food| %>
    <tr  id="<%= dom_id food %>">
			<td><%= food.food.name%></td>
      <td><%= food.quantity %></td>
			<td><%= food.food.price %>$</td>
			<td><%= food.food.measurement_unit %></td>
      <% if can? :update, @recipe%>
			<td><%= link_to "Modify",  edit_recipe_food_path(food.id), class: "btn btn-outline-info  fw-semibold fs-5 px-3" %></td> 
      <% end %>
      <% if can? :destroy, @recipe%>
			<td><%= link_to "Delete",  recipe_food_path(food.id),  data: { "turbo-method": :delete, confirm: "Are you sure ?" }, class: "btn btn-outline-danger  fw-semibold fs-5 px-3" %></td>
      <% end %>
    </tr>
  <% end %>
 </tbody>
</table>
</div>

<div>
  <%= link_to "Back to recipes", recipes_path, class: "btn btn-primary mt-5" %>
</div>
</div>