config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'foods#index'
  resources :public_recipes, only: [:index]
  resources :general_shoppings, only: [:index]
  resources :foods, only: [:index, :new, :create, :show, :destroy]
  resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    member do
      patch :public_toggle
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    user ||= User.new
    can :read, :all
    return unless user.present?

    can :manage, Recipe, user_id: user.id # if the user is logged in can manage it's own posts
    can :manage, Food, user_id: user.id # logged in users can also create comments
    can :manage, RecipeFood, user_id: user.id # logged in users can also create comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'food_id', dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'recipe_id', dependent: :destroy
  has_many :foods, through: :recipe_foods

  def total_price
    recipe_foods.sum { |food| food.quantity * food.food.price }
  end

  validates :name, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :description, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, class_name: 'Food', foreign_key: 'user_id', dependent: :destroy
  has_many :recipes, class_name: 'Recipe', foreign_key: 'user_id', dependent: :destroy
  has_many :recipe_foods, through: :recipes
  validates :name, presence: true, allow_blank: false, length: { maximum: 250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show destroy]

  # GET /foods or /foods.json
  def index
    @foods = current_user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.build(food_params)

    if @food.save
      flash[:notice] = 'Food was successfully created.'
      redirect_to foods_url(@food)
    else
      flash[:alert] = 'Food was not created.'
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy
    flash[:notice] = 'Food was successfully destroyed.'
    redirect_to foods_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @user = current_user
    @public_recipes = Recipe.includes(:user)
      .where(public: true)
      .order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_foods, only: %i[edit destroy update]
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_id: @recipe.id)
  end

  def create
    @recipe = Recipe.find(params[:recipe_food][:recipe_id])
    @recipe_food = @recipe.recipe_foods.build(recipe_food_params)
    if @recipe_food.save
      flash[:notice] = 'Food created successfully.'
      redirect_to recipe_url(user_id: current_user.id, id: @recipe.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @recipe_food.update(recipe_food_params)
      flash[:success] = 'Recipe Food updated successfully.'
    else
      flash[:alert] = 'Recipe Food not updated.'
    end
    redirect_to recipe_path(@recipe_food.recipe.id)
  end

  def destroy
    @recipe_food.destroy
    flash[:success] = 'Recipe Food deleted successfully.'
    recipes_url
  end

  private

  def set_recipe_foods
    @recipe_food = RecipeFood.includes(:recipe).find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show destroy public_toggle]

  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe_food = @recipe.recipe_foods.includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      flash[:notice] = 'Recipe was successfully created.'
      redirect_to recipes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe.destroy

    flash[:notice] = 'Recipe was successfully deleted.'
    redirect_to recipes_url
  end

  def public_toggle
    @recipe.public = !@recipe.public
    return unless @recipe.save

    redirect_to recipe_path(@recipe), notice: "The recipe is now #{@recipe.public ? 'public' : 'private'}"
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shoppings_helper.rb
module GeneralShoppingsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
<div class="alert alert-primary alert-dismissible" role="alert">
    <div class="fs-5 fw-bold">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
</div>
  <%end%>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-expand{-sm|-md|-lg|-xl|-xxl}" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><h2>RecipeApp</h2></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if current_user %>
         <li class="nav-item me-3"><%= link_to "Recipes List", recipes_path, class: "nav-link fw-bold text-primary" %></li>
         <li class="nav-item me-3"><%= link_to "Foods List", foods_path, class: "nav-link fw-bold text-primary" %></li>
         <li class="nav-item me-3"><%= link_to "Public Recipes", public_recipes_path, class: "nav-link fw-bold text-primary" %></li>
         <li class="nav-item me-3"><%= link_to "General Shopping", general_shoppings_path, class: "nav-link fw-bold text-primary" %></li>
         <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <%= render '/layouts/navbar'%>
   <%= render '/layouts/messages'%>
    <div class="container-fluid">
    <%= yield %>
    </div>
  </body>
</html>